server:
  port: 10005
spring:
  application:
    name: gateway-service
eureka:
  client:
    registry-fetch-interval-seconds: 5 # 获取服务列表的周期：5s
    service-url:
      defaultZone: http://127.0.0.1:10001/eureka
zuul:
  routes:
    service1: /userservice/**
  prefix: /api # 添加路由前缀

  hystrix:
    command:
      default:
        execution:
          isolation:
            thread:
              timeoutInMilliseconds: 6000 # 设置hystrix的超时时间为6000ms