server:
  port: 10004
spring:
  application:
    name: service3
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10001/eureka
      ##Eureka客户端与Eureka服务端的交互地址，高可用状态配置对方的地址，单机状态配置自己（如果
     #不配置则默认本机8761端口）
  instance:
    lease-renewal-interval-in-seconds: 5 # 5秒钟发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期